name: white_label_sdui
description: White-label payment portal with Server-Driven UI (sections by id).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/layouts/
